Added volume tweaker
sanket143/MJam pull request #62
Opened 2020-11-04 11:45 UTC by AjaysinhRajput2802

I have added volume tweaker on MJam and it is working fine.

2020-11-05 13:34 UTC, sanket143 commented
Replace .png images to material icons as it is already available to be used in the source code already. https://material.io/resources/icons/?style=baseline

Keep the state of the volume tweaker saved in the `localStorage` so that it could be same even after a restart.

Also, keep one PR just for one issue. So that you could get separate feedback for separate PRs.

2020-11-05 13:40 UTC, sanket143 requested changes

2020-11-05 13:40 UTC, sanket143 commented on scripts/components/content.js
> +      return Object.values(state.songsMap).sort() //Now we have sorted list of all_songs
A better solution will be to store the list already sorted in cache rather than sorting everytime when we launch the application.

2020-11-06 10:37 UTC, AjaysinhRajput2802 commented
> Keep the state of the volume tweaker saved in the `localStorage` so that it could be same even after a restart.

@sanket143 ,I have saved its state in `localStorage` but how to use it as volume-tweaker's value when I restart ?
I have tried many things but not able to get it, Can you please help me ?

2020-11-06 13:03 UTC, sanket143 commented
you can read value from `localStorage` and assign the same to volume tweaker.

2020-11-06 13:06 UTC, AjaysinhRajput2802 commented
> you can read value from `localStorage` and assign the same to volume tweaker.

but volume tweaker's value can only be a number from 0 to 100. we cannot assign it a variabel.

2020-11-06 15:14 UTC, sanket143 commented
MJam is using vue.js. I think you can make use of `v-model` https://vuejs.org/v2/guide/?#Handling-User-Input

2020-11-13 11:50 UTC, closed without merging

2020-11-13 11:51 UTC, AjaysinhRajput2802 commented
I will make Three seperate PR for this.